In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [83]:
data = pd.read_csv('processed.hungarian.data')
df = pd.DataFrame(data)

In [84]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,-1,-1,-1,0
1,29,1,2,120,243,0,0,160,0,0.0,-1,-1,-1,0
2,29,1,2,140,-1,0,0,170,0,0.0,-1,-1,-1,0
3,30,0,1,170,237,0,1,170,0,0.0,-1,-1,6,0
4,31,0,2,100,219,0,1,150,0,0.0,-1,-1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160,331,0,0,94,1,2.5,-1,-1,-1,1
290,54,0,3,130,294,0,1,100,1,0.0,2,-1,-1,1
291,56,1,4,155,342,1,0,150,1,3.0,2,-1,-1,1
292,58,0,2,180,393,0,0,110,1,1.0,2,-1,7,1
293,65,1,4,130,275,0,1,115,1,1.0,2,-1,-1,1

In [85]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
count,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000
mean,47.826531,0.724490,2.982993,132.129252,231.146259,0.040816,0.214286,138.653061,0.299320,0.586054,0.023810,-0.989796,-0.367347,0.360544
std,7.811812,0.447533,0.965117,19.243995,93.849322,0.306417,0.465536,24.927240,0.466121,0.908648,1.400674,0.100670,2.013882,0.480977
min,28.000000,0.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,42.000000,0.000000,2.000000,120.000000,198.000000,0.000000,0.000000,122.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000
50%,49.000000,1.000000,3.000000,130.000000,237.000000,0.000000,0.000000,140.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000
75%,54.000000,1.000000,4.000000,140.000000,277.000000,0.000000,0.000000,155.000000,1.000000,1.000000,2.000000,-1.000000,-1.000000,1.000000
max,66.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,190.000000,1.000000,5.000000,3.000000,0.000000,7.000000,1.000000

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       294 non-null    int64
 1   sex       294 non-null    int64
 2   cp        294 non-null    int64
 3   trestbps  294 non-null    int64
 4   chol      294 non-null    int64
 5   fbs       294 non-null    int64
 6   restecg   294 non-null    int64
 7   thalach   294 non-null    int64
 8   exang     294 non-null    int64
 9   oldpeak   294 non-null    float64
 10  slope     294 non-null    int64
 11  ca        294 non-null    int64
 12  thal      294 non-null    int64
 13  num       294 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.3 KB

## Drop useless column

In [87]:
df.drop('ca', axis=1, inplace=True)
df.drop('thal', axis=1, inplace=True)

In [88]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,num
0,28,1,2,130,132,0,2,185,0,0.0,-1,0
1,29,1,2,120,243,0,0,160,0,0.0,-1,0
2,29,1,2,140,-1,0,0,170,0,0.0,-1,0
3,30,0,1,170,237,0,1,170,0,0.0,-1,0
4,31,0,2,100,219,0,1,150,0,0.0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160,331,0,0,94,1,2.5,-1,1
290,54,0,3,130,294,0,1,100,1,0.0,2,1
291,56,1,4,155,342,1,0,150,1,3.0,2,1
292,58,0,2,180,393,0,0,110,1,1.0,2,1
293,65,1,4,130,275,0,1,115,1,1.0,2,1

# Change null value to mean value

In [148]:
for c in df.columns:
    df[df[c] == -1] = int(df[c].mean())

In [149]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,num
count,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.00000,294.000000,294.000000,294.000000,294.000000,294.000000
mean,47.826531,0.724490,2.982993,132.583618,250.848708,0.069930,0.21843,139.129693,0.303754,0.586054,1.894231,0.360544
std,7.811812,0.447533,0.965117,17.596463,64.947939,0.251964,0.46008,23.549459,0.459878,0.908648,0.200992,0.480977
min,28.000000,0.000000,1.000000,92.000000,85.000000,0.000000,0.00000,82.000000,0.000000,0.000000,1.000000,0.000000
25%,42.000000,0.000000,2.000000,120.000000,211.250000,0.000000,0.00000,122.000000,0.000000,0.000000,1.894231,0.000000
50%,49.000000,1.000000,3.000000,130.000000,248.500000,0.000000,0.00000,140.000000,0.000000,0.000000,1.894231,0.000000
75%,54.000000,1.000000,4.000000,140.000000,277.000000,0.000000,0.00000,155.000000,1.000000,1.000000,2.000000,1.000000
max,66.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.00000,190.000000,1.000000,5.000000,3.000000,1.000000

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       294 non-null    int64
 1   sex       294 non-null    int64
 2   cp        294 non-null    int64
 3   trestbps  294 non-null    float64
 4   chol      294 non-null    float64
 5   fbs       294 non-null    float64
 6   restecg   294 non-null    float64
 7   thalach   294 non-null    float64
 8   exang     294 non-null    float64
 9   oldpeak   294 non-null    float64
 10  slope     294 non-null    float64
 11  num       294 non-null    int64
dtypes: float64(8), int64(4)
memory usage: 27.7 KB

In [166]:
from sklearn.model_selection import train_test_split

x = df.drop('num', axis = 1)
y = df['num']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [167]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [168]:
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

In [169]:
from sklearn.metrics import accuracy_score

acc_train = accuracy_score(y_true=y_train, y_pred=y_pred_train)
acc_test = accuracy_score(y_true=y_test, y_pred=y_pred_test)

In [170]:
acc_train, acc_test

(0.8382978723404255, 0.8305084745762712)

In [156]:
from sklearn.metrics import confusion_matrix, recall_score, precision_score

confusion_matrix(y_test, y_pred_test)

array([[29,  4],
       [ 6, 20]])

In [157]:
precision_score(y_test, y_pred_test)

0.8333333333333334

In [158]:
recall_score(y_test, y_pred_test)

0.7692307692307693